### ISSUE TITLE
Welcome to the BLDS Data Discussion Group

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#1]
This is a discussion group for anyone interested in helping develop the Building & Land Development Specification (BLDS), BLDS is a format for publishing open data on building and construction permits issued by municipal governments. It is being developed by a coalition of interested parties, civic technology companies, governments and others with the hope that it will provide new insights into building and construction happening in communities and foster innovative approaches for displaying and consuming this information. 

The latest version of the BLDS standard can be [viewed here](https://docs.google.com/document/d/19F2I18MnqVa8-xrm6VGiSziJwniqE8rrYlx98lkTh3w/edit#). 

More information on this effort can be obtained by visiting permitdata.org.

**Comment by aditya180** [comment]
Is there an issue here or just review of the content?  Content looks fine.
