### ISSUE TITLE
Modify Data Types

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#10]
Modify data types to conform to [SQLite standard types](https://www.sqlite.org/datatype3.html).

Modify dates to conform to ISO-8601 date standard.

/cc: @eddietejeda, @jqnatividad, @ajturner

**Comment by jqnatividad** [comment]
Unless explicitly specified in the date/time field, timezone for all dates/times will default to the jurisdiction's timezone (ala GTFS - agency_timezone)

This means we need to capture the jurisdiction's timezone as an additional field.

**Comment by stevevance** [comment]
@jqnatividad Wouldn't it be safer to revert to UTC?

**Comment by jqnatividad** [comment]
@stevevance perhaps. 

But per ISO 8601, if timezone is unspecified in a date/time field, it represents local time, which means we still need to capture the jurisdiction's timezone as a required field, much the same way its required in GTFS - https://developers.google.com/transit/gtfs/reference#agency_fields

**Comment by aditya180** [comment]
Was already conforming to SQLite, but there was a mistake for dates that were left as NUMERIC as opposed to TEXT.  Fixed.
