### ISSUE TITLE
Modify Address Information

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#12]
Break address information out into its component parts - street number, street direction, street name, unit, unit type, suffix, suffix direction.

Add unit number.

/cc: @axtheset

**Comment by stevevance** [comment]
DataMade has a Python script [called usaddress](http://parserator.datamade.us/usaddress) that can parse addresses into these component parts. It could be useful for people who are looking to transform single-field address data.

**Comment by aditya180** [comment]
Per our WG discussion, and based on comments on data consumption side, I think we have agreed to keep the address information aggregated.

**Comment by mheadd** [comment]
Yes, since city, state and zip are already broken out that should provide sufficient granularity to group sort based on those fields.

**Comment by aditya180** [comment]
Okay.  I think this is resolved.
