### ISSUE TITLE
Unique Permit Number

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#15]
Permit number should be unique - should it be globally unique, across data publishers?

**Comment by mmartin78** [comment]
I don't believe permit number needs to be unique across publishers, seems like a big restriction to put on the spec. If some user of the data wants to make it unique for some application, they can combine with jurisdiction id to make it unique.

**Comment by mheadd** [comment]
Good point, I believe that same approach is used with the [Open311 spec](http://wiki.open311.org/GeoReport_v2/#definitions).

**Comment by aditya180** [comment]
Currently, the permit number does not indicate it needs to be unique.  Therefore, I think this is issue is closed.  Thanks.
