### ISSUE TITLE
Require Applied Date

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#16]
The current draft makes the date a permit is applied for optional:

```
Note that only one of the dates for AppliedDate, IssuedDate or CompletedDate is required.  
However, if all dates are available, all should be submitted.
```

Should applied date be required to ensure that - among other things - time from permit application to permit issuance can be calculated?

**Comment by aditya180** [comment]
I don't think.  This was brought up in past discussions, and due to variability in the data, the conclusion was to include what is available.

**Comment by mheadd** [comment]
Make AppliedDate optional & IssuedDate & CompletedDate or Status Current required?
