### ISSUE TITLE
Additional Values for "PermitTypeMapped" Field

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#19]
Sub headings under the **building** heading (to specify the type of building):
- New Construction
- Renovation/Alteration
- Tent

Also, add - as a separate category:
- Pool/Spa

/cc: @stevevance

**Comment by aditya180** [comment]
Pool/Spa is already included.  I think the first three bullets would be captured as part of WorkClass indicating whether a property is new or existing.

**Comment by mheadd** [comment]
FWIW, I also did a quick scan of a few of the publicly available BLDS data sets and there are very few mentions of 'tent' in the provided descriptions. Perhaps we should consider a new value of 'other' for instances where there is a specialized permit type..?
