### ISSUE TITLE
Update contact email

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#2]
Main page includes an [Accela email for interested parties to contact](https://github.com/open-data-standards/permitdata.org/blob/master/index.html#L188). This should probably be replaced at some point with something more generic.

**Comment by aditya180** [comment]
I suggest we remove this line "If you work for a government that is interested in publishing data in the BLDS format, you can get in touch here." until we figure how this will be governed.

**Comment by mheadd** [comment]
I think it would be good to have some facility for interested governments to reach out. Perhaps we can set up an email that directs inquiries from questions@permitdata.org to a wider audience.

Open to suggestions.

**Comment by eddietejeda** [comment]
Is email forwarding setup for permitdata.org? We should switch this.

**Comment by mheadd** [comment]
Not yet, but it could be. Will mark this item as in progress and work on that.
