### ISSUE TITLE
Specify projection & other details of coordinates

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#22]
@jqnatividad - Specify projection - WGS 84 Web Mercator.

@eddietejeda - I would love to see this but in working with a variety of agencies I've come to accept that they have their projections and it can be challenging to make them change. Since it's not that a big a challenge, we just do them ourselves. So I would highly encourage WGS 84 but I would not force it.

@jqnatividad - I see your point. In that case, we need to capture the projection, with the default being WGS 84 if not specified.

@stevevance - Coordinates of what? The building, the building's address, or the building's parcel centroid?

@rgradeck - Recommend using a parcel centroid or that the coordinate be located within the geographic bounds of the parcel to allow for geographic joins to other parcel data.

@ajturner - I know Lat/Lon are easier for spreadsheets. But this would be better if it were location or geography and can be GeoJSON. That way it can be a point or grow to be Lines (road segments) or polygons (footprint, park, etc.)

**Comment by aditya180** [comment]
Currently, the spec accepts location information in the form of an address, lat/long and parcel ID number.  Are coordinates and corresponding projection needed in addition?

**Comment by ajturner** [comment]
The Latitude and Longitude are the coordinates and there should be explicitly documented as WGS84 Mercator. 

For general centroid information that should be precise enough. This could be joined to a parcel layer in local projection for accuracy.

**Comment by aditya180** [comment]
Understood that WGS84 should be the norm, but is it something that needs to be forced?  My suggestion would be to add a Projection field after Lat/Long.  As long as we know what projection the coordinates are in, the data can be mapped and transformed to another projection if needed.  Keeps the standard more flexible, yet still allows use.

**Comment by mheadd** [comment]
/cc: @ajturner What are your thoughts on simply adding a new field for 'Projection' as suggested by @aditya180?

**Comment by aditya180** [comment]
An additional thought on this – another person commented that including a
‘Projection’ field isn’t the best approach as it would repeat this data for
every record.  I agree with this.  Normally, this type of thing would be
handled as part of the metadata, which we really haven’t addressed yet.

_From:_ Mark Headd [mailto:notifications@github.com]
_Sent:_ Friday, July 31, 2015 7:08 AM
_To:_ open-data-standards/permitdata.org permitdata.org@noreply.github.com
_Cc:_ Aditya Agrawal aditya.agrawal@socrata.com
_Subject:_ Re: [permitdata.org] Specify projection & other details of
coordinates (#22)

/cc: @ajturner https://github.com/ajturner What are your thoughts on
simply adding a new field for 'Projection' as suggested by @aditya180
https://github.com/aditya180?

**Comment by mheadd** [comment]
Will include in the meta information file for each dataset discussed in #45.

**Comment by mmartin78** [comment]
Following the GeoJSON standard seems like the logical thing to do here. See link: http://geojson.org/geojson-spec.html#coordinate-reference-system-objects
