### ISSUE TITLE
Remove redundant project cost fields

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#25]
There are two fields - _EstProjectCost_ and _EstProjectCostDec_ - that seem to include the same information. Redundant field should be removed.

/cc: @ajturner, @axtheset, @@c-sayre

**Comment by stevevance** [comment]
If there's a numeric field, to represent a numeric value, then there shouldn't be a text/string field.

**Comment by aditya180** [comment]
Removed redundant fields and only kept numeric value - EstProjectCost
