### ISSUE TITLE
Publisher and permitypedesc

### ISSUE THREAD

**Issue by axtheset** [open-data-standards/permitdata.org#41]
We should perhaps extract a few fields into a legends file or files.  For example the publisher field in the permit file should not have to be repeated with every record that should be in a feed_info file including other metadata.

Fields like permittypedesc and inspectiontypedesc should perhaps be extracted into a permit_legend or inspection_legend file perhaps.

**Comment by mheadd** [comment]
Closing this issue and addressing in #45.
