### ISSUE TITLE
Create an Interested Observer designation for the BLDS spec

### ISSUE THREAD

**Issue by mikehamel** [open-data-standards/permitdata.org#42]
It would be great if something like an "Interested Observer" designation, similar to the "Partners & Contributors" designation could be created.

Interested Observer might be defined as something like: Interested Observers listed below have expressed an interest in the BLDS Specification and are considering the implementation or recommendation of the standard.

Given that this effort is in its infancy, I cannot make the recommendation that communities should commit to this standard today. However, I would love to indicate that the Commonwealth of Massachusetts is looking at this, and encourage our various stakeholders to seriously evaluate and participate in the evolution of the specification. I also think indicating that large government organizations are interested would increase the credibility of the standard.

**Comment by mheadd** [comment]
This can be done by updating the BLDS website to list Interested Observers. Perhaps we should just require anyone wanting to be listed as such to submit an issue requesting that the name of their jurisdiction or organization be added.

**Comment by mikehamel** [comment]
That's great!  Just let me know if you need anything else from me to get the Commonwealth of Massachusetts listed as an interested observer. It would be great to continue the momentum following Boston's announcement.

**Comment by mheadd** [comment]
An interested observer section has [now been added](https://github.com/open-data-standards/permitdata.org/commit/76b8888303ccd0266d23c1b323bd79a0a15e8a3a) to the BLDS website.
