### ISSUE TITLE
Contact information for publishing jurisdiction?

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#45]
The [LIVES standard](http://www.yelp.com/healthscores) uses a "feed_info.csv" file to list contact information from the jurisdiction that is publishing data. This can come in handy when there are issues with a specific data set, and a consumer wants to contact a publishing jurisdiction directly.

Should the BLDS standard include similar information about a publishing jurisdiction - specifically, a contact email address or other contact mechanism?

**Comment by mmartin78** [comment]
This is what we have in OpenPermit for this, maybe you could use it as a start (Pardon the syntax), in the end we will adopt whatever variant:

public struct Agency
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public string Lastline { get; set; }
        public string Web { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    }

**Comment by aditya180** [comment]
I think this is a good idea.  We already have Publisher in the optional fields.  I would suggest adding PublisherEmail to optional.  Note that in recommended, we do have Link that could be used to go back to the jurisdiction's main website to where the data is made available.  Contact information should be present there.

**Comment by mmartin78** [comment]
@aditya180 I disagree with that approach and prefer @mheadd approach. The approach you suggest would unnecessarily add lots of duplicate data to the permits dataset (i.e. same email address for every record). 

This is also related to #41, perhaps should be merged?

**Comment by aditya180** [comment]
Good point. Agreed.

**Comment by mheadd** [comment]
Here is a proposed breakout for a new file that would contain contact information.

I tried to combine @mmartin78's class definition above with what the LIVES spec uses in a way that is consistent with the work the BLDS team has already done. 

As with the LIVES spec, this file would be an optional file to include when publishing BLDS data.

Thoughts?

/cc: @aditya180, @axtheset

## Required

| Field | DataType | Description |
| :-- | :-- | :-- |
| Jurisdiction | TEXT | Unique ID of jurisdiction |
| Version | NUMERIC | Version of the BLDS specification used to generate BLDS data. For example '1.0' |
| Email | TEXT | Email address of the person to contact regarding invalid data in this data file or feed |

## Recommended

| Field | DataType | Description |
| :-- | :-- | :-- |
| LastUpdate | TEXT (YYYY-MM-DD) | Date that the file or data feed was last updated |

## Optional

| Field | DataType | Description |
| :-- | :-- | :-- |
| URL | TEXT | URL where the jurisdiction publishes building permit data |
| Phone | TEXT | Telephone number of the person to contact regarding invalid data in this data file or feed |
| Fax | TEXT | Fax number of the person to contact regarding invalid data in this data file or feed |

**Comment by axtheset** [comment]
@mheadd maybe add an additional URL to their building department's landing page?  Consumers could find detailed permit descriptions, fee schedules, all sorts of things to help bolster the understanding of the data.

**Comment by mheadd** [comment]
Maybe that should be the content in the URL field, where the jurisdiction publishes building permit data, since the standard also accommodates a link to an individual building permit record...

**Comment by mmartin78** [comment]
@mheadd approach sounds good to me. People can also add that type of info in the "ExtraFields" column.

**Comment by mheadd** [comment]
We should also add the projection used for coordinates in this file. Discussed in more detail in #22.

**Comment by mheadd** [comment]
New wiki page [created](https://github.com/open-data-standards/permitdata.org/wiki/Optional-Dataset-Information-Requirements/_history) to capture this.
