### ISSUE TITLE
1.0? Announcement?

### ISSUE THREAD

**Issue by eddietejeda** [open-data-standards/permitdata.org#46]
Do we have a target date for announcing version 1.0?

**Comment by mheadd** [comment]
@eddietejeda Unless there are any outstanding issues, there isn't anything preventing us from making the announcement about v. 1.0.

**Comment by mheadd** [comment]
One [outstanding question](https://github.com/open-data-standards/permitdata.org/issues/47) raised.

**Comment by mheadd** [comment]
Outstanding issue resolved.

Draft announcement text is [here](https://docs.google.com/document/d/1UwU7qFmMOHPy0D7_bMAzOEhbU4V3FdjI_HsIQbw8qvQ/edit).

**Comment by mheadd** [comment]
I've posted the text of the draft announcement to the [BLDS website](http://permitdata.org/announcements.html) so that we can all refer to it as we do outreach. Hope this helps.

**Comment by eddietejeda** [comment]
:thumbsup:

**Comment by eddietejeda** [comment]
We can close this now.
