### ISSUE TITLE
Add Chicago Cityscape as a partner

### ISSUE THREAD

**Issue by stevevance** [open-data-standards/permitdata.org#5]
[Chicago Cityscape](http://chicagocityscape.com) is a website that ingests building permit data from the City of Chicago's open data portal (hosted by Socrata). The data is repackaged into a readable format, as well as visualized in various maps and charts. 

I think there should be more data points and the City of Chicago should be in the process right now of upgrading to a new permit software.

**Comment by mheadd** [comment]
Thanks, @stevevance - will get it added with the net bunch of changes. Thanks!

**Comment by stevevance** [comment]
I just saw now the difference between contributor and partner. I just added some comments to the draft spec, and some new fields. Can Cityscape be marked as a contributor?

**Comment by mheadd** [comment]
The initial distinction between contributor and partner was meant to denote those that had contributed to the initial draft (over a period of several months), and those that wanted to continue to develop it going forward.

That said, I can raise the issue with the other contributors and get some feedback.

**Comment by mheadd** [comment]
@stevevance Just started working on an [API for accessing data](https://github.com/Accela-Inc/permit-data-api) in this format. Early days, but would appreciate your thoughts or feedback. Thanks!

**Comment by stevevance** [comment]
@mheadd Right now the only thing I would change is the formatting of the headers to improve reading comprehension. LMK if you want me to change these. I've little experience with designing APIs but I'll see what I can add to the conversation...

**Comment by mheadd** [comment]
@stevevance Would love any thoughts. I haven't done anything to the response headers specifically, what the API serves is what nginx / expressjs provide out of the box.

<pre>
HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Tue, 21 Apr 2015 13:22:21 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1185
Connection: keep-alive
X-Powered-By: Express
ETag: W/"3862m/D++TrSbbKW9LbtmQ=="
</pre>
