### ISSUE TITLE
Error in "Housing Units" field

### ISSUE THREAD

**Issue by eddietejeda** [open-data-standards/permitdata.org#51]
There is a space in the field label "Housing Units." To be consistent with other field names, this space should be removed.

https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements

**Comment by mheadd** [comment]
Good catch. Fixed.

**Comment by eddietejeda** [comment]
Can we add CHANGELOG.md to repo to list these edits (even if minor)?

**Comment by mheadd** [comment]
@eddietejeda : Each wiki page has a [revision history](https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements/_history) (wikis are actually self contained git repos).

Do you think this works? Or should we create a stand along page for this?

**Comment by eddietejeda** [comment]
Oh, that works. Lets link to that on the front page titled CHANGES or CHANGELOG.

**Comment by mheadd** [comment]
Added a [CHANGELOG file](https://github.com/open-data-standards/permitdata.org/blob/gh-pages/CHANGELOG.md) to point to the history of the wiki pages.
