### ISSUE TITLE
Dates and Status

### ISSUE THREAD

**Issue by aditya180** [open-data-standards/permitdata.org#52]
Adjust required fields so that AppliedDate OR IssuedDate is required AND CompletedDate OR StatusCurrent required.  

Reason being is that in some cases, AppliedDate and StatusCurrent are provided that indicate a date for filing the permit and what the status is including categories such as issued or completed.  By only requiring IssuedDate where AppliedDate is only offered with the Status, the dataset would be non-compliant even if it provides all the core requirements the standard is looking for.

**Comment by mheadd** [comment]
@aditya180 Is this an issue that you are seeing in actual datasets that are published (or being published) or is it an issue that you think could happen in some jurisdictions?

If it's an issue that is affecting currently published datasets, can you provide an example?

**Comment by aditya180** [comment]
Mark.  I've already explained this several times as part of the working group.  It is an issue with data I am seeing and will be an issue for other data sets.

**Comment by mheadd** [comment]
@aditya180 The purpose of this list of issues is to provide transparency around the discussions of the group working on this standard. To be honest, I'm looking for more detail myself as I want to be able to evaluate how serious an issue this is, and to help determine if this is something that should be addressed in another release.

Also, I think it is important that others on this issues list and those with an interest in the BLDS standard have a chance to see and comment on pending issues.

I think its pretty reasonable to ask for details on where and how often this issue has come up.

**Comment by aditya180** [comment]
Mark,

Understood.  The issue is this:  If you have AppliedDate and Status, that
meets the requirement of the standard which is to have some indication
around timing and the stage the permit is in.  Some datasets have only
AppliedDate, without IssuedDate, as Issued or other status is indicated in
the Status fields.  AppliedDate was previously an option for required
before we made the change, and therefore, datasets that don’t have
IssuedDate, but do have AppliedDate and a Status are non-compliant.  I
think this is a mistake which is why I am requesting a change.  By having
AppliedDate or IssuedDate with some indication of status including
CompletedDate would be a much more flexible approach to getting the
information needed.

Aditya

_From:_ Mark Headd [mailto:notifications@github.com]
_Sent:_ Friday, July 24, 2015 8:45 AM
_To:_ open-data-standards/permitdata.org
_Cc:_ Aditya Agrawal
_Subject:_ Re: [permitdata.org] Dates and Status (#52)

@aditya180 https://github.com/aditya180 The purpose of this list of
issues is to provide transparency around the discussions of the group
working on this standard. To be honest, I'm looking for more detail myself
as I want to be able to evaluate how serious an issue this is, and to help
determine if this is something that should be addressed in another release.

Also, I think it is important that others on this issues list and those
with an interest in the BLDS standard have a chance to see and comment on
pending issues.

I think its pretty reasonable to ask for details on where and how often
this issue has come up.

**Comment by mheadd** [comment]
Updated [wiki page](https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements/_history) to reflect this change.
