### ISSUE TITLE
Please add us as a partner

### ISSUE THREAD

**Issue by natelaclaire** [open-data-standards/permitdata.org#54]
At [Home Building Estimates](http://homebuildingestimates.com/) we work closely with everyone involved in the residential building sector. We are excited by your work and would like to participate.

**Comment by mheadd** [comment]
@natelaclaire Apologies for the delay on this - will get the process of adding your organization moving. Thanks!

**Comment by natelaclaire** [comment]
@mheadd No problem! Thanks! We're looking forward to working with you!

**Comment by mheadd** [comment]
@natelaclaire Our steering committee met last week and added your organization as a partner. You'll now find the name of you organization listed on the [project website](http://permitdata.org/#partners).

Please feel free to publicize your support for the BLDS standard via public outreach or by sharing with your network.

If you have any questions, don't hesitate to open an issue or send an email to questions@permitdata.org.

Thanks!
