### ISSUE TITLE
Please add Eastlake Data as a partner

### ISSUE THREAD

**Issue by trivisonno** [open-data-standards/permitdata.org#62]
Eastlake Data would like to participate as a partner for this specification.  Our website is https://eastlakedata.org.

Best,
Angelo

**Comment by mheadd** [comment]
@trivisonno Apologies for the delay on this - will get the process of adding your organization moving. Thanks!

**Comment by mheadd** [comment]
@trivisonno Our steering committee met last week and added your organization as a partner. You'll now find the name of you organization listed on the [project website](http://permitdata.org/#partners).

Please feel free to publicize your support for the BLDS standard via public outreach or by sharing with your network.

If you have any questions, don't hesitate to open an issue or send an email to questions@permitdata.org.

Thanks!
