### ISSUE TITLE
Clarify requirement for OriginalAddress2

### ISSUE THREAD

**Issue by mheadd** [open-data-standards/permitdata.org#63]
I believe this field was meant to accommodate additional address information for a permit location when such information was stored as part of the permit record. If this data is stored by the jurisdiction, it should be included but if a jurisdiction does not store this information, should it be excluded? Should it be included with a blank value?

The standard should clarify the requirement for this data element.

**Comment by jqnatividad** [comment]
To clarify, can we use OriginalAddress2 to store special identifiers like Building Id Number in NYC?  Or is there a better place to store alternative entity identifiers used by the jurisdiction? http://www.nyc.gov/html/dob/html/bis/glossary.shtml

**Comment by mheadd** [comment]
OriginalAddress2 specifically mentions 'street address' information.

While probably not ideal, there is the `ExtraFields` field...

Is building ID a commonly used descriptor outside of NYC?

**Comment by jqnatividad** [comment]
Its an NYC-specific thing.  A more generic identifier with wider usage is tax block/lot.  Is that universal enough, or goes into Extras as well?

**Comment by mheadd** [comment]
This is a good topic for discussion. Let's target the next meeting, and I will try and have someone with insight into other jurisdictions on the call as well. Perhaps this warrants the addition of a specific field.

You want to create a new issue?

**Comment by jqnatividad** [comment]
New issue created - #73
