### ISSUE TITLE
CartoDB is interested in being a partner

### ISSUE THREAD

**Issue by rogerkeren** [open-data-standards/permitdata.org#72]
Woo Hoo!

Please contact me with confirmation.

**Comment by mheadd** [comment]
@rogerkeren Awesome!

**Comment by trivisonno** [comment]
Great news! @EastlakeData uses CartoDB extensively for zoning and tax revenue study, and will add permit data to the mix once we start receiving it from the local government.

**Comment by mheadd** [comment]
:+1:

**Comment by mheadd** [comment]
@rogerkeren Our steering committee met last week and added your organization as a partner. You'll now find the name of you organization listed on the [project website](http://permitdata.org/#partners).

Please feel free to publicize your support for the BLDS standard via public outreach or by sharing with your network.

If you have any questions, don't hesitate to open an issue or send an email to questions@permitdata.org.

Thanks!
