### ISSUE TITLE
Consider adding tax block/lot to recommended or optional fields

### ISSUE THREAD

**Issue by jqnatividad** [open-data-standards/permitdata.org#73]
as this is often a more stable identifier that can also be used to crosswalk other jurisdiction datasets (i.e. property tax)

**Comment by jqnatividad** [comment]
On second thought, required might be too stringent, perhaps recommended or optional.

**Comment by jqnatividad** [comment]
a.k.a. Assessor's parcel number, Assessor's identification number, Property identification number, Property Account number, tax id number, parcel identification number, sidwell number, borough block lot (NYC), etc.

https://en.wikipedia.org/wiki/Assessor%27s_parcel_number

**Comment by mheadd** [comment]
In Philadelphia, its referred to as [OPA or BRT number](http://metadata.phila.gov/#home/datasetdetails/5543866020583086178c4ee7/representationdetails/55f31aad49daa3bf75aa77f3/) (OPA = Office of Property Assessment, BRT = Board of Revision of Taxes [deprecated]).

**Comment by mheadd** [comment]
Some proposed language for adding a new `Parcel ID` filed to the list of recommended fields in the [Core Permit Dataset](https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements). 

### Recommended

| Field | DataType | Description |
| :-- | :-- | :-- |
| Parcel ID | TEXT | Unique identifier for a land parcel within a jurisdiction. The identifier may be colloquially referred to as assessor's ID, tax ID, parcel number, etc. |

**Comment by mheadd** [comment]
Related to [this issue](https://github.com/open-data-standards/permitdata.org/issues/76) about multi-parcel permits.

**Comment by jqnatividad** [comment]
What about this expanded description?

"Primary unique identifier for a land parcel within a jurisdiction used for tax assessment purposes. The identifier may be colloquially referred to as assessor's ID, tax ID, parcel number, etc."

**Comment by mheadd** [comment]
Makes sense to me. Will wait to hear if others offer suggestions and update here when the change is finalized.

**Comment by bettin** [comment]
How is this different than the "PIN" field in the Recommended list which is for "Parcel Identification Number"
https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements#recommended

**Comment by mheadd** [comment]
@bettin: Hmm, perhaps we should update the existing PIN field with the description provided by @jqnatividad. I missed that when I reviewed this issue. I think the intent in including it was to address the kinds of issue Joel raised, but the description as is isn't very helpful.

Thoughts?

**Comment by mheadd** [comment]
Closed with [this change](https://github.com/open-data-standards/permitdata.org/wiki/Core-Permits-Dataset-Requirements/_compare/5879c5ac962249fd3f8bd58d3b0948b1abb4e8a5...50cf48430e6b4d90369ec944fd1d1bcc2c4a833d).
