### ISSUE TITLE
Spatial Data Logic is interested in being a partner

### ISSUE THREAD

**Issue by bFlood** [open-data-standards/permitdata.org#74]
We provide software to 100+ municipalities in NJ
https://www.spatialdatalogic.com

in our Construction Module, permits can be tracked and viewed online. We'd like to support the BLDS spec for external access to the permit data. here is a sample map of one of our clients (Jersey City, NJ), you can filter by permit date/status/work type/total cost.
https://www.sdlportal.com/towns/nj/hudson/jerseycity/maps?vid=permits

**Comment by jqnatividad** [comment]
:+1:  Awesome!
And we're currently working with Spatial Data Logic to have a BLDS implementation in Jersey City!

**Comment by mheadd** [comment]
@bFlood Thanks for reaching out! Will be adding orgs to the list of members in January. Will follow up with you when that is completed. Thanks!

**Comment by mheadd** [comment]
@bFlood Our steering committee met last week and added your organization as a partner. You'll now find the name of you organization listed on the [project website](http://permitdata.org/#partners).

Please feel free to publicize your support for the BLDS standard via public outreach or by sharing with your network.

If you have any questions, don't hesitate to open an issue or send an email to questions@permitdata.org.

Thanks!
