### ISSUE TITLE
AmigoCloud wants to support BLDS

### ISSUE THREAD

**Issue by rburhum** [open-data-standards/permitdata.org#75]
We are doing some implementations in the Bay Area to integrate several permit / zoning data from various enterprise systems. We have been thinking for using BLDS as the intermediate format for all permit data. We'd love to be involved.

**Comment by mheadd** [comment]
Thanks, @rburhum! let us know what we can do to help or any additional details we can provide.

**Comment by mheadd** [comment]
@rburhum Our steering committee met last week and added your organization as a partner. You'll now find the name of you organization listed on the [project website](http://permitdata.org/#partners).

Please feel free to publicize your support for the BLDS standard via public outreach or by sharing with your network.

If you have any questions, don't hesitate to open an issue or send an email to questions@permitdata.org.

Thanks!
